stages:
  - build
  - test
  - deploy

variables:
  ANSIBLE_PLAYBOOK: "deploy.yml"   # Путь к playbook
  ANSIBLE_HOSTS: "hosts"          # Путь к файлу hosts

build:
  stage: build
  tags: 
      - build
  image: golang:1.24.9
  script:
    - go build -o app
  artifacts:
    paths:
      - app

test:
  stage: test
  tags: 
      - test
  image: golang:1.24.9
  script:
    - go test ./...

deploy:
  stage: deploy
  tags: 
      - deploy
  image: ubuntu:24.04
  script:
    - apt update
    - apt install -y ansible sudo
    - useradd -m testing
    - usermod -aG sudo testing
    - mkdir -p /home/testing/.ssh
    - chmod 700 /home/testing/.ssh
    - chown testing:testing /home/testing/.ssh
    - su - testing -c "ssh-keygen -t ed25519 -f /home/testing/.ssh/id_rsa -N ''"
    - su - testing -c "chmod 600 /home/testing/.ssh/id_rsa"
    - su - testing -c "ssh-copy-id -i /home/testing/.ssh/id_rsa.pub 192.168.1.101"
    - su - testing -c "ssh-keyscan 192.168.1.101 >> /home/testing/.ssh/known_hosts"
    - su - testing -c "ansible-playbook -i $ANSIBLE_HOSTS $ANSIBLE_PLAYBOOK --become"
  only:
    - master
