stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REGISTRY: http://192.168.1.50:8929

build:
  stage: build
  image: golang:1.24.9
  script:
    - go build -o app
  artifacts:
    paths:
      - app

test:
  stage: test
  image: golang:1.24.9
  script:
    - go test ./...

deploy:
  stage: deploy
  image: docker:20.10.24
  script:
    - docker build -t $DOCKER_REGISTRY/app .
    - docker push $DOCKER_REGISTRY/app
  only:
    - master
