stages:
  - build
  - test
  - deploy

variables:
  ANSIBLE_PLAYBOOK: "deploy.yml"   # Путь к playbook
  ANSIBLE_HOSTS: "hosts"          # Путь к файлу hosts

build:
  stage: build
  tags: 
      - build
  image: golang:1.24.9
  script:
    - go build -o app
  artifacts:
    paths:
      - app

test:
  stage: test
  tags: 
      - test
  image: golang:1.24.9
  script:
    - go test ./...

deploy:
  stage: deploy
  tags: 
      - deploy
  image: ubuntu:24.04
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - export ANSIBLE_PRIVATE_KEY_FILE=~/.ssh/id_ed25519
    - ssh-keyscan -H 192.168.1.101 >> ~/.ssh/known_hosts
  script:
    - apt update
    - apt install -y ansible
    - apt purge -y ansible
    - apt autoremove -y
    - ansible --version
    - ansible-playbook -i $ANSIBLE_HOSTS $ANSIBLE_PLAYBOOK --become --module-path=/root/.ansible/collections/plugins/modules
  only:
    - master
