stages:
  - build
  - test
  - deploy

variables:
  DOCKER_REGISTRY: 192.168.1.50:8929
  DEPLOY_USER: testing
  DEPLOY_SERVER: "192.168.1.50" 

build:
  stage: build
  tags: 
      - build
  image: golang:1.24.9
  script:
    - go build -o app
  artifacts:
    paths:
      - app

test:
  stage: test
  tags: 
      - test
  image: golang:1.24.9
  script:
    - go test ./...


deploy:
  stage: deploy
  tags: 
      - deploy
#  image: docker:20.10.24
  script:
    - scp app $DEPLOY_USER@$DEPLOY_SERVER:/deploy
#    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USER" 192.168.1.50:8929 --password-stdin
#    - docker build -t $DOCKER_REGISTRY/app .
#    - docker push $DOCKER_REGISTRY/app
  only:
    - master
